# Generated by Django 5.1.1 on 2024-09-05 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visa_type', models.CharField(max_length=100)),
                ('visa_type_description', models.CharField(max_length=200)),
                ('visa_type_duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VisaApplication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('form_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=200)),
                ('passport_number', models.CharField(max_length=20)),
                ('passport_issue_date', models.DateField()),
                ('passport_expiry_date', models.DateField()),
                ('passport_photo', models.ImageField(default='images/default.jpg', upload_to='images')),
                ('visa_start_date', models.DateField()),
                ('visa_type_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visa_type_reference', to='api.visatype')),
            ],
        ),
    ]
