# Generated by Django 5.1.1 on 2024-09-05 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_visatype_visaapplication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
