# Generated by Django 5.1.1 on 2024-09-06 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visaapplication',
            name='passport_photo',
            field=models.ImageField(default='images/default.jpg', upload_to='images'),
        ),
    ]
